config/routes.rb
Floridabiblestudy::Application.routes.draw do
  
  resources :events
  resources :faqs
  root :to => "welcome#index"
  match '/registration/register' => "registration#register"
  match ':controller(/:action(/:id(.:format)))'
  
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController

   # GET /faqs
   # GET /faqs.xml
   def index
      @title = 'Frequently Asked Questions'
      @faqs = Faq.find(:all, :conditions => "publish = true", :order => 'list_order')
      respond_to do |format|
         format.html # index.html.erb
         format.xml  { render :xml => @faqs }
      end
   end

  # GET /faqs/1
  # GET /faqs/1.xml
  def show
    @faq = Faq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @faq }
    end
  end

end

app/views/faqs/edit.html.erb
<h1>Editing Faq</h1>

<%= error_messages_for :faq %>

<% form_for(@faq) do |f| %>
  <p>Blah</p>
<% end %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<h1>Frequently Asked Questions</h1>

<p>Here are some questions that sometimes come up and the answers to them.</p>

<% for faq in @faqs %>
   <h2><%= faq.title %></h2>
   <p><%= faq.body %></p>
<% end %>

app/views/faqs/list.html.erb
<h1>Frequently Asked Questions</h1>

<% for faq in @faqs %>
   <h2>[# <%= faq.list_order %> ]<%= faq.title %></h2>
   <% if faq.publish %>
      <%= ( unpublish ) %>
   <% else %>
      <%= ( publish ) %>
   <% end %>
   <p><%= faq.body %></p>
   <hr />
<% end %>

app/views/faqs/new.html.erb
<h1>New Faq</h1>

<%= error_messages_for :faq %>

<% form_for(@faq) do |f| %>
  <p>blah</p>
<% end %>

<%= link_to 'Back', faqs_path %>